from conf import PROJECT_NAME
from utils.fileHelper import readFile

data = readFile(PROJECT_NAME, ['conf.json'])

COOKIE_SOURCE = data['COOKIE-SOURCE']
COOKIE_REDIS_NAME = data['COOKIE-SOURCE-REDIS-NAME']
COOKIE_FILE_PATH = data['COOKIE-SOURCE-FILE-PATHS']

PROXY_SOURCE = data['PROXIES-SOURCE']
PROXY_REDIS_NAME = data['PROXIES-SOURCE-REDIS-NAME']
PROXY_FILE_PATH = data['PROXIES-SOURCE-FILE-PATHS']


SAVE2TASK_CENTER = data['SAVE2TASK-CENTER']
SAVE2DATABASES = data['SAVE2DATABASES']
ALLOW_TASK_DISTRIBUTE = data['ALLOW-TASK-DISTRIBUTE']
MIN_PUSH_COUNT = data['MIN-PUSH-COUNT']
